import type { ErrorCode, ErrorInfo } from '@/types/error.types';

export const ERROR_INFO_MAP: Record<ErrorCode, ErrorInfo> = {
  UNKNOWN_ERROR: {
    code: 'UNKNOWN_ERROR',
    message: 'An unknown error occurred',
    severity: 'high',
    category: 'system',
    recoverable: false,
    retryable: true,
    userMessage: '发生了未知错误，请稍后重试',
  },
  NETWORK_ERROR: {
    code: 'NETWORK_ERROR',
    message: 'Network connection failed',
    severity: 'medium',
    category: 'network',
    recoverable: true,
    retryable: true,
    userMessage: '网络连接失败，请检查网络后重试',
  },
  TIMEOUT_ERROR: {
    code: 'TIMEOUT_ERROR',
    message: 'Request timeout',
    severity: 'medium',
    category: 'network',
    recoverable: true,
    retryable: true,
    userMessage: '请求超时，请稍后重试',
  },
  VALIDATION_ERROR: {
    code: 'VALIDATION_ERROR',
    message: 'Validation failed',
    severity: 'low',
    category: 'validation',
    recoverable: true,
    retryable: false,
    userMessage: '输入数据验证失败',
  },
  AUTH_ERROR: {
    code: 'AUTH_ERROR',
    message: 'Authentication failed',
    severity: 'high',
    category: 'auth',
    recoverable: false,
    retryable: false,
    userMessage: '认证失败，请重新登录',
  },
  TOKEN_EXPIRED: {
    code: 'TOKEN_EXPIRED',
    message: 'Token has expired',
    severity: 'medium',
    category: 'auth',
    recoverable: true,
    retryable: false,
    userMessage: '登录已过期，请重新登录',
  },
  TOKEN_INVALID: {
    code: 'TOKEN_INVALID',
    message: 'Token is invalid',
    severity: 'high',
    category: 'auth',
    recoverable: false,
    retryable: false,
    userMessage: '无效的认证信息，请重新登录',
  },
  PERMISSION_ERROR: {
    code: 'PERMISSION_ERROR',
    message: 'Permission denied',
    severity: 'medium',
    category: 'permission',
    recoverable: false,
    retryable: false,
    userMessage: '没有权限执行此操作',
  },
  NOT_FOUND_ERROR: {
    code: 'NOT_FOUND_ERROR',
    message: 'Resource not found',
    severity: 'medium',
    category: 'resource',
    recoverable: false,
    retryable: false,
    userMessage: '请求的资源不存在',
  },
  CONFLICT_ERROR: {
    code: 'CONFLICT_ERROR',
    message: 'Resource conflict',
    severity: 'medium',
    category: 'resource',
    recoverable: true,
    retryable: false,
    userMessage: '资源冲突，请刷新后重试',
  },
  RATE_LIMIT_ERROR: {
    code: 'RATE_LIMIT_ERROR',
    message: 'Rate limit exceeded',
    severity: 'medium',
    category: 'system',
    recoverable: true,
    retryable: true,
    userMessage: '请求过于频繁，请稍后重试',
  },
  FILE_TYPE_ERROR: {
    code: 'FILE_TYPE_ERROR',
    message: 'Invalid file type',
    severity: 'low',
    category: 'file',
    recoverable: true,
    retryable: false,
    userMessage: '不支持的文件类型',
  },
  FILE_SIZE_ERROR: {
    code: 'FILE_SIZE_ERROR',
    message: 'File size exceeds limit',
    severity: 'low',
    category: 'file',
    recoverable: true,
    retryable: false,
    userMessage: '文件大小超出限制',
  },
  FILE_REGISTER_FAILED: {
    code: 'FILE_REGISTER_FAILED',
    message: 'File register failed',
    severity: 'medium',
    category: 'file',
    recoverable: true,
    retryable: true,
    userMessage: '文件注册失败，请重试',
  },
  FILE_CORRUPTED: {
    code: 'FILE_CORRUPTED',
    message: 'File is corrupted',
    severity: 'medium',
    category: 'file',
    recoverable: false,
    retryable: false,
    userMessage: '文件已损坏',
  },
  UPLOAD_ERROR: {
    code: 'UPLOAD_ERROR',
    message: 'File upload failed',
    severity: 'medium',
    category: 'file',
    recoverable: true,
    retryable: true,
    userMessage: '文件上传失败，请重试',
  },
  DOWNLOAD_ERROR: {
    code: 'DOWNLOAD_ERROR',
    message: 'File download failed',
    severity: 'medium',
    category: 'file',
    recoverable: true,
    retryable: true,
    userMessage: '文件下载失败，请重试',
  },
  NODE_ERROR: {
    code: 'NODE_ERROR',
    message: 'Node operation failed',
    severity: 'medium',
    category: 'workflow',
    recoverable: true,
    retryable: false,
    userMessage: '节点操作失败',
  },
  NODE_NOT_FOUND: {
    code: 'NODE_NOT_FOUND',
    message: 'Node not found',
    severity: 'medium',
    category: 'workflow',
    recoverable: false,
    retryable: false,
    userMessage: '节点不存在',
  },
  NODE_LOCKED: {
    code: 'NODE_LOCKED',
    message: 'Node is locked',
    severity: 'low',
    category: 'workflow',
    recoverable: true,
    retryable: false,
    userMessage: '节点已锁定，无法编辑',
  },
  WORKFLOW_ERROR: {
    code: 'WORKFLOW_ERROR',
    message: 'Workflow operation failed',
    severity: 'medium',
    category: 'workflow',
    recoverable: true,
    retryable: false,
    userMessage: '工作流操作失败',
  },
  WORKFLOW_NOT_FOUND: {
    code: 'WORKFLOW_NOT_FOUND',
    message: 'Workflow not found',
    severity: 'medium',
    category: 'workflow',
    recoverable: false,
    retryable: false,
    userMessage: '工作流不存在',
  },
  WORKFLOW_VERSION_CONFLICT: {
    code: 'WORKFLOW_VERSION_CONFLICT',
    message: 'Workflow version conflict',
    severity: 'medium',
    category: 'workflow',
    recoverable: true,
    retryable: false,
    userMessage: '工作流已被其他用户修改，请刷新',
  },
  AI_TASK_ERROR: {
    code: 'AI_TASK_ERROR',
    message: 'AI task failed',
    severity: 'medium',
    category: 'ai',
    recoverable: true,
    retryable: true,
    userMessage: 'AI任务执行失败',
  },
  AI_TASK_TIMEOUT: {
    code: 'AI_TASK_TIMEOUT',
    message: 'AI task timeout',
    severity: 'medium',
    category: 'ai',
    recoverable: true,
    retryable: true,
    userMessage: 'AI任务执行超时',
  },
  AI_TASK_CANCELLED: {
    code: 'AI_TASK_CANCELLED',
    message: 'AI task cancelled',
    severity: 'low',
    category: 'ai',
    recoverable: false,
    retryable: false,
    userMessage: 'AI任务已取消',
  },
  AI_PROVIDER_ERROR: {
    code: 'AI_PROVIDER_ERROR',
    message: 'AI provider error',
    severity: 'high',
    category: 'ai',
    recoverable: true,
    retryable: true,
    userMessage: 'AI服务暂时不可用',
  },
  AI_RATE_LIMIT: {
    code: 'AI_RATE_LIMIT',
    message: 'AI rate limit exceeded',
    severity: 'medium',
    category: 'ai',
    recoverable: true,
    retryable: true,
    userMessage: 'AI服务请求过于频繁，请稍后重试',
  },
  RENDER_ERROR: {
    code: 'RENDER_ERROR',
    message: 'Render error',
    severity: 'high',
    category: 'system',
    recoverable: true,
    retryable: false,
    userMessage: '渲染错误，请刷新页面',
  },
  WEBSOCKET_ERROR: {
    code: 'WEBSOCKET_ERROR',
    message: 'WebSocket error',
    severity: 'medium',
    category: 'network',
    recoverable: true,
    retryable: true,
    userMessage: '实时连接错误',
  },
  WEBSOCKET_DISCONNECTED: {
    code: 'WEBSOCKET_DISCONNECTED',
    message: 'WebSocket disconnected',
    severity: 'medium',
    category: 'network',
    recoverable: true,
    retryable: true,
    userMessage: '实时连接已断开，正在重连...',
  },
  STORAGE_ERROR: {
    code: 'STORAGE_ERROR',
    message: 'Storage error',
    severity: 'medium',
    category: 'system',
    recoverable: true,
    retryable: false,
    userMessage: '存储错误',
  },
  STORAGE_QUOTA_EXCEEDED: {
    code: 'STORAGE_QUOTA_EXCEEDED',
    message: 'Storage quota exceeded',
    severity: 'high',
    category: 'system',
    recoverable: false,
    retryable: false,
    userMessage: '存储空间不足',
  },
};
